### ISSUE TITLE
所以如何解决部分词语的转换错误呢？

### ISSUE THREAD

**Issue by zyfdegh** [semicircle/gozhszht#1]
:question: `沙特阿拉伯` -> `沙乌地阿拉伯`
:no_entry_sign: `乾隆` -> `干隆`
:no_entry_sign: `東加拿大` -> `汤加拿大`

**Comment by semicircle** [comment]
正如 readme 所说, 这个库其实做不了词级别的转换, 建议试试 google translate 的 API

**Comment by zyfdegh** [comment]
了解，谢谢。Closing
